const {
  API_PORT,
  MAX_NUMBER_OF_MESSAGES_PER_REQUEST,
  PROCESSING_WAITING_TIME_IN_SECONDS
} = process.env

export default {
  API_PORT,
  QUEUE: {
    MAX_NUMBER_OF_MESSAGES_PER_REQUEST,
    PROCESSING_WAITING_TIME_IN_SECONDS
  }
}
